import "es6-promise/auto";

export * from "./http/http";
export * from "./auth/auth";
export * as models from "./models/all";
export { createConfiguration, Configuration, ConfigurationParameters } from "./configuration"
export * from "./apis/exception";
export * from "./servers";

export { PromiseMiddleware as Middleware } from './middleware';
export { PromiseAaaApi as AaaApi,  PromiseAdapterApi as AdapterApi,  PromiseApplianceApi as ApplianceApi,  PromiseAssetApi as AssetApi,  PromiseBiosApi as BiosApi,  PromiseBootApi as BootApi,  PromiseComputeApi as ComputeApi,  PromiseCondApi as CondApi,  PromiseConnectorpackApi as ConnectorpackApi,  PromiseDeviceconnectorApi as DeviceconnectorApi,  PromiseEquipmentApi as EquipmentApi,  PromiseEtherApi as EtherApi,  PromiseExternalsiteApi as ExternalsiteApi,  PromiseFaultApi as FaultApi,  PromiseFcApi as FcApi,  PromiseFeedbackApi as FeedbackApi,  PromiseFirmwareApi as FirmwareApi,  PromiseForecastApi as ForecastApi,  PromiseGraphicsApi as GraphicsApi,  PromiseHclApi as HclApi,  PromiseHyperflexApi as HyperflexApi,  PromiseIaasApi as IaasApi,  PromiseIamApi as IamApi,  PromiseInventoryApi as InventoryApi,  PromiseIpmioverlanApi as IpmioverlanApi,  PromiseKvmApi as KvmApi,  PromiseLicenseApi as LicenseApi,  PromiseLsApi as LsApi,  PromiseManagementApi as ManagementApi,  PromiseMemoryApi as MemoryApi,  PromiseMetaApi as MetaApi,  PromiseNetworkApi as NetworkApi,  PromiseNetworkconfigApi as NetworkconfigApi,  PromiseNiaapiApi as NiaapiApi,  PromiseNiatelemetryApi as NiatelemetryApi,  PromiseNtpApi as NtpApi,  PromiseOrganizationApi as OrganizationApi,  PromiseOsApi as OsApi,  PromisePciApi as PciApi,  PromisePortApi as PortApi,  PromiseProcessorApi as ProcessorApi,  PromiseRecoveryApi as RecoveryApi,  PromiseResourceApi as ResourceApi,  PromiseSdcardApi as SdcardApi,  PromiseSdwanApi as SdwanApi,  PromiseSearchApi as SearchApi,  PromiseSecurityApi as SecurityApi,  PromiseServerApi as ServerApi,  PromiseSmtpApi as SmtpApi,  PromiseSnmpApi as SnmpApi,  PromiseSoftwareApi as SoftwareApi,  PromiseSoftwarerepositoryApi as SoftwarerepositoryApi,  PromiseSolApi as SolApi,  PromiseSshApi as SshApi,  PromiseStorageApi as StorageApi,  PromiseSyslogApi as SyslogApi,  PromiseTamApi as TamApi,  PromiseTaskApi as TaskApi,  PromiseTelemetryApi as TelemetryApi,  PromiseTerminalApi as TerminalApi,  PromiseTopApi as TopApi,  PromiseUcsdApi as UcsdApi,  PromiseVirtualizationApi as VirtualizationApi,  PromiseVmediaApi as VmediaApi,  PromiseVnicApi as VnicApi,  PromiseWorkflowApi as WorkflowApi } from './types/PromiseAPI';

