/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplianceNodeInfoAllOf } from './ApplianceNodeInfoAllOf';
import { CommIpV4Interface } from './CommIpV4Interface';
import { MoBaseMo } from './MoBaseMo';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { HttpFile } from '../http/http';

/**
* NodeInfo managed object stores the Intersight Appliance's cluster node information. NodeInfo managed objects are created during the Intersight Appliance setup. The Intersight Appliance updates the NodeInfo managed objects with status information periodically.
*/
export class ApplianceNodeInfo extends MoBaseMo {
    /**
    * Cluster node's FQDN or IP address.
    */
    'hostname'?: string;
    /**
    * System assigned unique ID of the Intersight Appliance node. The system incrementally assigns identifiers to each node in the Intersight Appliance cluster starting with a value of 1.
    */
    'nodeId'?: number;
    'nodeIpV4Config'?: CommIpV4Interface;
    /**
    * Operational status of the Intersight Appliance node.
    */
    'operationalStatus'?: ApplianceNodeInfoOperationalStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hostname",
            "baseName": "Hostname",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodeId",
            "baseName": "NodeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "nodeIpV4Config",
            "baseName": "NodeIpV4Config",
            "type": "CommIpV4Interface",
            "format": ""
        },
        {
            "name": "operationalStatus",
            "baseName": "OperationalStatus",
            "type": "ApplianceNodeInfoOperationalStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ApplianceNodeInfo.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}


export type ApplianceNodeInfoOperationalStatusEnum = "Unknown" | "Operational" | "Impaired" | "AttentionNeeded" ;

