/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplianceDeviceClaimAllOf } from './ApplianceDeviceClaimAllOf';
import { IamAccountRelationship } from './IamAccountRelationship';
import { MoBaseMo } from './MoBaseMo';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { HttpFile } from '../http/http';

/**
* DeviceClaim managed object represents a user initiated claim request for claiming an endpoint device. There can be many DeviceClaim managed object for a given endpoint device when users claim and unclaim devices repeatedly. Claiming an endpoint device is a multi-step operation. The Intersight Appliance starts a workflow with multiple tasks to process the device claim request. The status of the device claim operation can be obtained from the claim workflow.
*/
export class ApplianceDeviceClaim extends MoBaseMo {
    /**
    * Device identifier of the endpoint device.
    */
    'deviceId'?: string;
    /**
    * Hostname or IP address of the endpoint device the user wants to claim.
    */
    'hostname'?: string;
    /**
    * Indicates whether the value of the 'password' property has been set.
    */
    'isPasswordSet'?: boolean;
    /**
    * Message set by the device claim process.
    */
    'message'?: string;
    /**
    * Password to be used to login to the endpoint device.
    */
    'password'?: string;
    /**
    * Platform type of the endpoint device.
    */
    'platformType'?: ApplianceDeviceClaimPlatformTypeEnum;
    /**
    * User defined claim request identifier set by the UI. The RequestId field is not a mandatory. The Intersight Appliance will assign a unique value automatically if the field is not set.
    */
    'requestId'?: string;
    /**
    * Device security token of the endpoint device.
    */
    'securityToken'?: string;
    /**
    * Status of the device claim process.
    */
    'status'?: ApplianceDeviceClaimStatusEnum;
    /**
    * Username to log in to the endpoint device.
    */
    'username'?: string;
    'account'?: IamAccountRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deviceId",
            "baseName": "DeviceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "hostname",
            "baseName": "Hostname",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPasswordSet",
            "baseName": "IsPasswordSet",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "Message",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "Password",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformType",
            "baseName": "PlatformType",
            "type": "ApplianceDeviceClaimPlatformTypeEnum",
            "format": ""
        },
        {
            "name": "requestId",
            "baseName": "RequestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "securityToken",
            "baseName": "SecurityToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "Status",
            "type": "ApplianceDeviceClaimStatusEnum",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "Username",
            "type": "string",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "Account",
            "type": "IamAccountRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ApplianceDeviceClaim.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}


export type ApplianceDeviceClaimPlatformTypeEnum = "" | "APIC" | "DCNM" | "UCSFI" | "UCSFIISM" | "IMC" | "IMCM4" | "IMCM5" | "UCSIOM" | "HX" | "HyperFlexAP" | "UCSD" | "IntersightAppliance" | "PureStorageFlashArray" | "NetAppOntap" | "EmcScaleIo" | "EmcVmax" | "EmcVplex" | "EmcXtremIo" | "VmwareVcenter" | "MicrosoftHyperV" | "AppDynamics" | "Dynatrace" | "MicrosoftSqlServer" | "Kubernetes" | "MicrosoftAzure" | "ServiceEngine" | "IMCBlade" ;
export type ApplianceDeviceClaimStatusEnum = "started" | "failed" | "completed" ;

