/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetConnection } from './AssetConnection';
import { AssetCredential } from './AssetCredential';
import { AssetHttpConnectionAllOf } from './AssetHttpConnectionAllOf';
import { HttpFile } from '../http/http';

/**
* HttpConnection provides the necessary details for Intersight to connect to and authenticate with a managed target over an HTTP connection.
*/
export class AssetHttpConnection extends AssetConnection {
    'credential'?: AssetCredential;
    /**
    * Indicates whether a connection to the target should be established using HTTPS.
    */
    'isSecure'?: boolean;
    /**
    * The DNS hostname or IP Address, either IPv4 or IPv6, to be used to connect to the managed target.
    */
    'managementAddress'?: string;
    /**
    * The port number to be used to to connect to the managed target. Values 1-65535 indicate a port number to be used. A value of 0 is not a valid port number and instead indicates that the default management port, as defined by the documentation of the managed target, should be used to establish a connection.
    */
    'port'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credential",
            "baseName": "Credential",
            "type": "AssetCredential",
            "format": ""
        },
        {
            "name": "isSecure",
            "baseName": "IsSecure",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "managementAddress",
            "baseName": "ManagementAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "Port",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AssetHttpConnection.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}

