/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetClusterMemberRelationship } from './AssetClusterMemberRelationship';
import { AssetDeviceClaimRelationship } from './AssetDeviceClaimRelationship';
import { AssetDeviceConfigurationRelationship } from './AssetDeviceConfigurationRelationship';
import { AssetDeviceRegistration } from './AssetDeviceRegistration';
import { AssetParentConnectionSignature } from './AssetParentConnectionSignature';
import { IamAccountRelationship } from './IamAccountRelationship';
import { IamDomainGroupRelationship } from './IamDomainGroupRelationship';
import { IamUserRelationship } from './IamUserRelationship';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoMoRef } from './MoMoRef';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { HttpFile } from '../http/http';

/**
* A relationship to the 'asset.DeviceRegistration' resource, or the expanded 'asset.DeviceRegistration' resource, or the 'null' value.
*/
export class AssetDeviceRegistrationRelationship {
    /**
    * The Account ID for this managed object.
    */
    'accountMoid'?: string;
    /**
    * The concrete type of this complex type. Its value must be the same as the 'objectType' property. The OpenAPI document references this property as a discriminator value.
    */
    'classId': string;
    /**
    * The time when this managed object was created.
    */
    'createTime'?: Date;
    /**
    * The DomainGroup ID for this managed object.
    */
    'domainGroupMoid'?: string;
    /**
    * The time when this managed object was last modified.
    */
    'modTime'?: Date;
    /**
    * The unique identifier of this Managed Object instance.
    */
    'moid'?: string;
    /**
    * The fully-qualified type of this managed object, i.e. the class name. This property is optional. The ObjectType is implied from the URL path. If specified, the value of objectType must match the class name specified in the URL path.
    */
    'objectType': string;
    'owners'?: Array<string>;
    /**
    * Intersight provides pre-built workflows, tasks and policies to end users through global catalogs. Objects that are made available through global catalogs are said to have a 'shared' ownership. Shared objects are either made globally available to all end users or restricted to end users based on their license entitlement. Users can use this property to differentiate the scope (global or a specific license tier) to which a shared MO belongs.
    */
    'sharedScope'?: string;
    'tags'?: Array<MoTag>;
    'versionContext'?: MoVersionContext;
    /**
    * An array of relationships to moBaseMo resources.
    */
    'ancestors'?: Array<MoBaseMoRelationship>;
    'parent'?: MoBaseMoRelationship;
    /**
    * An array of relationships to moBaseMo resources.
    */
    'permissionResources'?: Array<MoBaseMoRelationship>;
    /**
    * a map of display names for a resource.
    */
    'displayNames'?: { [key: string]: Array<string>; };
    /**
    * The version of the connector API, describes the capability of the connector's framework. If the version is lower than the current minimum supported version defined in the service managing the connection, the device connector will be connected with limited capabilities until the device connector is upgraded to a fully supported version. For example if a device connector that was released without delta inventory capabilities registers and connects to Intersight, inventory collection may be disabled until it has been upgraded.
    */
    'apiVersion'?: number;
    /**
    * The partition number corresponding to the instance of the Proxy App which is managing the web-socket to the device connector.
    */
    'appPartitionNumber'?: number;
    /**
    * The unique identifier for the current connection. The identifier persists across network connectivity loss and is reset on device connector process restart or platform administrator toggle of the Intersight connectivity. The connectionId can be used by services that need to interact with stateful plugins running in the device connector process. For example if a service schedules an inventory in a devices job scheduler plugin at registration it is not necessary to reschedule the job if the device loses network connectivity due to an Intersight service upgrade or intermittent network issues in the devices datacenter.
    */
    'connectionId'?: string;
    /**
    * If 'connectionStatus' is not equal to Connected, connectionReason provides further details about why the device is not connected with Intersight.
    */
    'connectionReason'?: string;
    /**
    * The status of the persistent connection between the device connector and Intersight.
    */
    'connectionStatus'?: AssetDeviceRegistrationRelationshipConnectionStatusEnum;
    /**
    * The last time at which the 'connectionStatus' property value changed. If connectionStatus is Connected, this time can be interpreted as the starting time since which a persistent connection has been maintained between Intersight and Device Connector. If connectionStatus is NotConnected, this time can be interpreted as the last time the device connector was connected with Intersight.
    */
    'connectionStatusLastChangeTime'?: Date;
    /**
    * The version of the device connector running on the managed device.
    */
    'connectorVersion'?: string;
    /**
    * The IP Address of the managed device as seen from Intersight at the time of registration. This could be the IP address of the managed device's interface which has a route to the internet or a NAT IP addresss when the managed device is deployed in a private network.
    */
    'deviceExternalIpAddress'?: string;
    /**
    * The name of the app which will proxy the messages to the device connector.
    */
    'proxyApp'?: string;
    /**
    * An identifier for the credential used by the device connector to authenticate with the Intersight web socket gateway.
    */
    'accessKeyId'?: string;
    /**
    * The name of the user who claimed the device for the account.
    */
    'claimedByUserName'?: string;
    /**
    * The date and time at which the device was claimed to this account.
    */
    'claimedTime'?: Date;
    'deviceHostname'?: Array<string>;
    'deviceIpAddress'?: Array<string>;
    /**
    * Indicates if the platform is an actual device or an emulated device for testing, demos, etc. Permitted values are [Normal, Emulator, ContainerEmulator].
    */
    'executionMode'?: AssetDeviceRegistrationRelationshipExecutionModeEnum;
    'parentSignature'?: AssetParentConnectionSignature;
    'pid'?: Array<string>;
    /**
    * The platform type on which device connector is executing.
    */
    'platformType'?: AssetDeviceRegistrationRelationshipPlatformTypeEnum;
    /**
    * The device connector's public key used by Intersight to authenticate a connection from the device connector. The public key is used to verify that the signature a device connector sends on connect has been signed by the connector's private key stored on the device's filesystem. Must be a PEM encoded RSA public key string.
    */
    'publicAccessKey'?: string;
    /**
    * Flag reported by devices to indicate an administrator of the device has disabled management operations of the device connector and only monitoring is permitted.
    */
    'readOnly'?: boolean;
    'serial'?: Array<string>;
    /**
    * The vendor of the managed device.
    */
    'vendor'?: string;
    'account'?: IamAccountRelationship;
    'claimedByUser'?: IamUserRelationship;
    /**
    * An array of relationships to assetClusterMember resources.
    */
    'clusterMembers'?: Array<AssetClusterMemberRelationship>;
    'deviceClaim'?: AssetDeviceClaimRelationship;
    'deviceConfiguration'?: AssetDeviceConfigurationRelationship;
    'domainGroup'?: IamDomainGroupRelationship;
    'parentConnection'?: AssetDeviceRegistrationRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountMoid",
            "baseName": "AccountMoid",
            "type": "string",
            "format": ""
        },
        {
            "name": "classId",
            "baseName": "ClassId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createTime",
            "baseName": "CreateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "domainGroupMoid",
            "baseName": "DomainGroupMoid",
            "type": "string",
            "format": ""
        },
        {
            "name": "modTime",
            "baseName": "ModTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "moid",
            "baseName": "Moid",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "ObjectType",
            "type": "string",
            "format": ""
        },
        {
            "name": "owners",
            "baseName": "Owners",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sharedScope",
            "baseName": "SharedScope",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "Tags",
            "type": "Array<MoTag>",
            "format": ""
        },
        {
            "name": "versionContext",
            "baseName": "VersionContext",
            "type": "MoVersionContext",
            "format": ""
        },
        {
            "name": "ancestors",
            "baseName": "Ancestors",
            "type": "Array<MoBaseMoRelationship>",
            "format": ""
        },
        {
            "name": "parent",
            "baseName": "Parent",
            "type": "MoBaseMoRelationship",
            "format": ""
        },
        {
            "name": "permissionResources",
            "baseName": "PermissionResources",
            "type": "Array<MoBaseMoRelationship>",
            "format": ""
        },
        {
            "name": "displayNames",
            "baseName": "DisplayNames",
            "type": "{ [key: string]: Array<string>; }",
            "format": ""
        },
        {
            "name": "apiVersion",
            "baseName": "ApiVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "appPartitionNumber",
            "baseName": "AppPartitionNumber",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "connectionId",
            "baseName": "ConnectionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionReason",
            "baseName": "ConnectionReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionStatus",
            "baseName": "ConnectionStatus",
            "type": "AssetDeviceRegistrationRelationshipConnectionStatusEnum",
            "format": ""
        },
        {
            "name": "connectionStatusLastChangeTime",
            "baseName": "ConnectionStatusLastChangeTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "connectorVersion",
            "baseName": "ConnectorVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "deviceExternalIpAddress",
            "baseName": "DeviceExternalIpAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "proxyApp",
            "baseName": "ProxyApp",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessKeyId",
            "baseName": "AccessKeyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "claimedByUserName",
            "baseName": "ClaimedByUserName",
            "type": "string",
            "format": ""
        },
        {
            "name": "claimedTime",
            "baseName": "ClaimedTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deviceHostname",
            "baseName": "DeviceHostname",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "deviceIpAddress",
            "baseName": "DeviceIpAddress",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "executionMode",
            "baseName": "ExecutionMode",
            "type": "AssetDeviceRegistrationRelationshipExecutionModeEnum",
            "format": ""
        },
        {
            "name": "parentSignature",
            "baseName": "ParentSignature",
            "type": "AssetParentConnectionSignature",
            "format": ""
        },
        {
            "name": "pid",
            "baseName": "Pid",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "platformType",
            "baseName": "PlatformType",
            "type": "AssetDeviceRegistrationRelationshipPlatformTypeEnum",
            "format": ""
        },
        {
            "name": "publicAccessKey",
            "baseName": "PublicAccessKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "readOnly",
            "baseName": "ReadOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "serial",
            "baseName": "Serial",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "vendor",
            "baseName": "Vendor",
            "type": "string",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "Account",
            "type": "IamAccountRelationship",
            "format": ""
        },
        {
            "name": "claimedByUser",
            "baseName": "ClaimedByUser",
            "type": "IamUserRelationship",
            "format": ""
        },
        {
            "name": "clusterMembers",
            "baseName": "ClusterMembers",
            "type": "Array<AssetClusterMemberRelationship>",
            "format": ""
        },
        {
            "name": "deviceClaim",
            "baseName": "DeviceClaim",
            "type": "AssetDeviceClaimRelationship",
            "format": ""
        },
        {
            "name": "deviceConfiguration",
            "baseName": "DeviceConfiguration",
            "type": "AssetDeviceConfigurationRelationship",
            "format": ""
        },
        {
            "name": "domainGroup",
            "baseName": "DomainGroup",
            "type": "IamDomainGroupRelationship",
            "format": ""
        },
        {
            "name": "parentConnection",
            "baseName": "ParentConnection",
            "type": "AssetDeviceRegistrationRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetDeviceRegistrationRelationship.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type AssetDeviceRegistrationRelationshipConnectionStatusEnum = "" | "Connected" | "NotConnected" | "ClaimInProgress" | "Unclaimed" ;
export type AssetDeviceRegistrationRelationshipExecutionModeEnum = "" | "Normal" | "Emulator" | "ContainerEmulator" ;
export type AssetDeviceRegistrationRelationshipPlatformTypeEnum = "" | "APIC" | "DCNM" | "UCSFI" | "UCSFIISM" | "IMC" | "IMCM4" | "IMCM5" | "UCSIOM" | "HX" | "HyperFlexAP" | "UCSD" | "IntersightAppliance" | "PureStorageFlashArray" | "NetAppOntap" | "EmcScaleIo" | "EmcVmax" | "EmcVplex" | "EmcXtremIo" | "VmwareVcenter" | "MicrosoftHyperV" | "AppDynamics" | "Dynatrace" | "MicrosoftSqlServer" | "Kubernetes" | "MicrosoftAzure" | "ServiceEngine" | "IMCBlade" ;

