/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetDeviceRegistrationRelationship } from './AssetDeviceRegistrationRelationship';
import { ComputeBladeRelationship } from './ComputeBladeRelationship';
import { ComputeRackUnitRelationship } from './ComputeRackUnitRelationship';
import { EquipmentTpmRelationship } from './EquipmentTpmRelationship';
import { GraphicsCardRelationship } from './GraphicsCardRelationship';
import { MemoryArrayRelationship } from './MemoryArrayRelationship';
import { MemoryPersistentMemoryConfigurationRelationship } from './MemoryPersistentMemoryConfigurationRelationship';
import { PciCoprocessorCardRelationship } from './PciCoprocessorCardRelationship';
import { PciSwitchRelationship } from './PciSwitchRelationship';
import { ProcessorUnitRelationship } from './ProcessorUnitRelationship';
import { SecurityUnitRelationship } from './SecurityUnitRelationship';
import { StorageControllerRelationship } from './StorageControllerRelationship';
import { StorageFlexFlashControllerRelationship } from './StorageFlexFlashControllerRelationship';
import { StorageFlexUtilControllerRelationship } from './StorageFlexUtilControllerRelationship';
import { HttpFile } from '../http/http';

/**
* Definition of the list of properties defined in 'compute.Board', excluding properties defined in parent classes.
*/
export class ComputeBoardAllOf {
    /**
    * The id of the mother board located in the server.
    */
    'boardId'?: number;
    'cpuTypeController'?: string;
    /**
    * Current power state of the mother board of the server.
    */
    'operPowerState'?: string;
    /**
    * Identifies the presence of the mother board of the server.
    */
    'presence'?: string;
    'computeBlade'?: ComputeBladeRelationship;
    'computeRackUnit'?: ComputeRackUnitRelationship;
    /**
    * An array of relationships to equipmentTpm resources.
    */
    'equipmentTpms'?: Array<EquipmentTpmRelationship>;
    /**
    * An array of relationships to graphicsCard resources.
    */
    'graphicsCards'?: Array<GraphicsCardRelationship>;
    /**
    * An array of relationships to memoryArray resources.
    */
    'memoryArrays'?: Array<MemoryArrayRelationship>;
    /**
    * An array of relationships to pciCoprocessorCard resources.
    */
    'pciCoprocessorCards'?: Array<PciCoprocessorCardRelationship>;
    /**
    * An array of relationships to pciSwitch resources.
    */
    'pciSwitch'?: Array<PciSwitchRelationship>;
    'persistentMemoryConfiguration'?: MemoryPersistentMemoryConfigurationRelationship;
    /**
    * An array of relationships to processorUnit resources.
    */
    'processors'?: Array<ProcessorUnitRelationship>;
    'registeredDevice'?: AssetDeviceRegistrationRelationship;
    /**
    * An array of relationships to securityUnit resources.
    */
    'securityUnits'?: Array<SecurityUnitRelationship>;
    /**
    * An array of relationships to storageController resources.
    */
    'storageControllers'?: Array<StorageControllerRelationship>;
    /**
    * An array of relationships to storageFlexFlashController resources.
    */
    'storageFlexFlashControllers'?: Array<StorageFlexFlashControllerRelationship>;
    /**
    * An array of relationships to storageFlexUtilController resources.
    */
    'storageFlexUtilControllers'?: Array<StorageFlexUtilControllerRelationship>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "boardId",
            "baseName": "BoardId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "cpuTypeController",
            "baseName": "CpuTypeController",
            "type": "string",
            "format": ""
        },
        {
            "name": "operPowerState",
            "baseName": "OperPowerState",
            "type": "string",
            "format": ""
        },
        {
            "name": "presence",
            "baseName": "Presence",
            "type": "string",
            "format": ""
        },
        {
            "name": "computeBlade",
            "baseName": "ComputeBlade",
            "type": "ComputeBladeRelationship",
            "format": ""
        },
        {
            "name": "computeRackUnit",
            "baseName": "ComputeRackUnit",
            "type": "ComputeRackUnitRelationship",
            "format": ""
        },
        {
            "name": "equipmentTpms",
            "baseName": "EquipmentTpms",
            "type": "Array<EquipmentTpmRelationship>",
            "format": ""
        },
        {
            "name": "graphicsCards",
            "baseName": "GraphicsCards",
            "type": "Array<GraphicsCardRelationship>",
            "format": ""
        },
        {
            "name": "memoryArrays",
            "baseName": "MemoryArrays",
            "type": "Array<MemoryArrayRelationship>",
            "format": ""
        },
        {
            "name": "pciCoprocessorCards",
            "baseName": "PciCoprocessorCards",
            "type": "Array<PciCoprocessorCardRelationship>",
            "format": ""
        },
        {
            "name": "pciSwitch",
            "baseName": "PciSwitch",
            "type": "Array<PciSwitchRelationship>",
            "format": ""
        },
        {
            "name": "persistentMemoryConfiguration",
            "baseName": "PersistentMemoryConfiguration",
            "type": "MemoryPersistentMemoryConfigurationRelationship",
            "format": ""
        },
        {
            "name": "processors",
            "baseName": "Processors",
            "type": "Array<ProcessorUnitRelationship>",
            "format": ""
        },
        {
            "name": "registeredDevice",
            "baseName": "RegisteredDevice",
            "type": "AssetDeviceRegistrationRelationship",
            "format": ""
        },
        {
            "name": "securityUnits",
            "baseName": "SecurityUnits",
            "type": "Array<SecurityUnitRelationship>",
            "format": ""
        },
        {
            "name": "storageControllers",
            "baseName": "StorageControllers",
            "type": "Array<StorageControllerRelationship>",
            "format": ""
        },
        {
            "name": "storageFlexFlashControllers",
            "baseName": "StorageFlexFlashControllers",
            "type": "Array<StorageFlexFlashControllerRelationship>",
            "format": ""
        },
        {
            "name": "storageFlexUtilControllers",
            "baseName": "StorageFlexUtilControllers",
            "type": "Array<StorageFlexUtilControllerRelationship>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComputeBoardAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

