/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetDeviceRegistrationRelationship } from './AssetDeviceRegistrationRelationship';
import { CondAlarmAllOf } from './CondAlarmAllOf';
import { MoBaseMo } from './MoBaseMo';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { HttpFile } from '../http/http';

/**
* A state-full entity representing a found problem. Alarms can be reported by the managed system itself or can be determined by Intersight.
*/
export class CondAlarm extends MoBaseMo {
    /**
    * MoId of the affected object from the managed system's point of view.
    */
    'affectedMoId'?: string;
    /**
    * Managed system affected object type. For example Adaptor, FI, CIMC.
    */
    'affectedMoType'?: string;
    /**
    * A unique key for an alarm instance, consists of a combination of a unique system name and msAffectedObject.
    */
    'affectedObject'?: string;
    /**
    * Parent MoId of the fault from managed system. For example, Blade moid for adaptor fault.
    */
    'ancestorMoId'?: string;
    /**
    * Parent MO type of the fault from managed system. For example, Blade for adaptor fault.
    */
    'ancestorMoType'?: string;
    /**
    * A unique alarm code. For alarms mapped from UCS faults, this will be the same as the UCS fault code.
    */
    'code'?: string;
    /**
    * The time the alarm was created.
    */
    'creationTime'?: Date;
    /**
    * A longer description of the alarm than the name. The description contains details of the component reporting the issue.
    */
    'description'?: string;
    /**
    * The time the alarm last had a change in severity.
    */
    'lastTransitionTime'?: Date;
    /**
    * A unique key for the alarm from the managed system's point of view. For example, in the case of UCS, this is the fault's dn.
    */
    'msAffectedObject'?: string;
    /**
    * Uniquely identifies the type of alarm. For alarms originating from Intersight, this will be a descriptive name. For alarms that are mapped from faults, the name will be derived from fault properties. For example, alarms mapped from UCS faults will use a prefix of UCS and appended with the fault code.
    */
    'name'?: string;
    /**
    * The original severity when the alarm was first created.
    */
    'origSeverity'?: CondAlarmOrigSeverityEnum;
    /**
    * The severity of the alarm. Valid values are Critical, Warning, Info, and Cleared.
    */
    'severity'?: CondAlarmSeverityEnum;
    'registeredDevice'?: AssetDeviceRegistrationRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedMoId",
            "baseName": "AffectedMoId",
            "type": "string",
            "format": ""
        },
        {
            "name": "affectedMoType",
            "baseName": "AffectedMoType",
            "type": "string",
            "format": ""
        },
        {
            "name": "affectedObject",
            "baseName": "AffectedObject",
            "type": "string",
            "format": ""
        },
        {
            "name": "ancestorMoId",
            "baseName": "AncestorMoId",
            "type": "string",
            "format": ""
        },
        {
            "name": "ancestorMoType",
            "baseName": "AncestorMoType",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "Code",
            "type": "string",
            "format": ""
        },
        {
            "name": "creationTime",
            "baseName": "CreationTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastTransitionTime",
            "baseName": "LastTransitionTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "msAffectedObject",
            "baseName": "MsAffectedObject",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "origSeverity",
            "baseName": "OrigSeverity",
            "type": "CondAlarmOrigSeverityEnum",
            "format": ""
        },
        {
            "name": "severity",
            "baseName": "Severity",
            "type": "CondAlarmSeverityEnum",
            "format": ""
        },
        {
            "name": "registeredDevice",
            "baseName": "RegisteredDevice",
            "type": "AssetDeviceRegistrationRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(CondAlarm.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}


export type CondAlarmOrigSeverityEnum = "None" | "Info" | "Critical" | "Warning" | "Cleared" ;
export type CondAlarmSeverityEnum = "None" | "Info" | "Critical" | "Warning" | "Cleared" ;

