/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetDeviceRegistrationRelationship } from './AssetDeviceRegistrationRelationship';
import { ComputeRackUnitRelationship } from './ComputeRackUnitRelationship';
import { EquipmentChassisRelationship } from './EquipmentChassisRelationship';
import { EquipmentRackEnclosureRelationship } from './EquipmentRackEnclosureRelationship';
import { NetworkElementRelationship } from './NetworkElementRelationship';
import { HttpFile } from '../http/http';

/**
* Definition of the list of properties defined in 'equipment.Psu', excluding properties defined in parent classes.
*/
export class EquipmentPsuAllOf {
    /**
    * This field is to provide description for the power supply unit.
    */
    'description'?: string;
    'operState'?: string;
    /**
    * This field identifies the Part Number for this Power Supply Unit.
    */
    'partNumber'?: string;
    /**
    * This field identifies the Product ID for the Power Supply.
    */
    'pid'?: string;
    /**
    * This field identifies the presence state of the psu.
    */
    'presence'?: string;
    /**
    * This field identifies the Firmware Version of the Power Supply.
    */
    'psuFwVersion'?: string;
    'psuId'?: number;
    /**
    * This field identifies the input source for the Power Supply.
    */
    'psuInputSrc'?: string;
    /**
    * This field identifies the type of the Power Supply.
    */
    'psuType'?: string;
    /**
    * This field identifies the Wattage of the Power Supply.
    */
    'psuWattage'?: string;
    /**
    * This field identifies the Stockkeeping Unit for this Power Supply.
    */
    'sku'?: string;
    /**
    * This field identifies the Vendor ID for this Power Supply Unit.
    */
    'vid'?: string;
    /**
    * This field is used to indicate the Voltage for this Power Supply.
    */
    'voltage'?: string;
    'computeRackUnit'?: ComputeRackUnitRelationship;
    'equipmentChassis'?: EquipmentChassisRelationship;
    'equipmentRackEnclosure'?: EquipmentRackEnclosureRelationship;
    'networkElement'?: NetworkElementRelationship;
    'registeredDevice'?: AssetDeviceRegistrationRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "operState",
            "baseName": "OperState",
            "type": "string",
            "format": ""
        },
        {
            "name": "partNumber",
            "baseName": "PartNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "pid",
            "baseName": "Pid",
            "type": "string",
            "format": ""
        },
        {
            "name": "presence",
            "baseName": "Presence",
            "type": "string",
            "format": ""
        },
        {
            "name": "psuFwVersion",
            "baseName": "PsuFwVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "psuId",
            "baseName": "PsuId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "psuInputSrc",
            "baseName": "PsuInputSrc",
            "type": "string",
            "format": ""
        },
        {
            "name": "psuType",
            "baseName": "PsuType",
            "type": "string",
            "format": ""
        },
        {
            "name": "psuWattage",
            "baseName": "PsuWattage",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "Sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "vid",
            "baseName": "Vid",
            "type": "string",
            "format": ""
        },
        {
            "name": "voltage",
            "baseName": "Voltage",
            "type": "string",
            "format": ""
        },
        {
            "name": "computeRackUnit",
            "baseName": "ComputeRackUnit",
            "type": "ComputeRackUnitRelationship",
            "format": ""
        },
        {
            "name": "equipmentChassis",
            "baseName": "EquipmentChassis",
            "type": "EquipmentChassisRelationship",
            "format": ""
        },
        {
            "name": "equipmentRackEnclosure",
            "baseName": "EquipmentRackEnclosure",
            "type": "EquipmentRackEnclosureRelationship",
            "format": ""
        },
        {
            "name": "networkElement",
            "baseName": "NetworkElement",
            "type": "NetworkElementRelationship",
            "format": ""
        },
        {
            "name": "registeredDevice",
            "baseName": "RegisteredDevice",
            "type": "AssetDeviceRegistrationRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EquipmentPsuAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

