/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForecastCatalogRelationship } from './ForecastCatalogRelationship';
import { ForecastDefinitionAllOf } from './ForecastDefinitionAllOf';
import { MoBaseMo } from './MoBaseMo';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { HttpFile } from '../http/http';

/**
* Definition for forecast metric settings.
*/
export class ForecastDefinition extends MoBaseMo {
    /**
    * Threshold above which user needs to be indicated through alarm/alert.
    */
    'alertThresholdInPercentage'?: number;
    /**
    * Data source from where we get the data for the metrics to compute regression model. For example Druid.
    */
    'dataSource'?: string;
    /**
    * Metric for which forecast prediction is done. Metrics are defined in the catalog file. Currently its only HyperFlex cluster storage capacity usage.
    */
    'metricName'?: string;
    /**
    * Minimum number of days of data required for computing forecast model.
    */
    'minNumOfDaysOfData'?: number;
    /**
    * Number of days of data queried from the data source (example Druid ) which is used as input data for computing forecast model.
    */
    'numOfDaysOfHistoricalData'?: number;
    /**
    * The platform type for which we want to compute forecast. For example HyperFlex, NetworkElement.
    */
    'platformType'?: string;
    'catalog'?: ForecastCatalogRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "alertThresholdInPercentage",
            "baseName": "AlertThresholdInPercentage",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "dataSource",
            "baseName": "DataSource",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricName",
            "baseName": "MetricName",
            "type": "string",
            "format": ""
        },
        {
            "name": "minNumOfDaysOfData",
            "baseName": "MinNumOfDaysOfData",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numOfDaysOfHistoricalData",
            "baseName": "NumOfDaysOfHistoricalData",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "platformType",
            "baseName": "PlatformType",
            "type": "string",
            "format": ""
        },
        {
            "name": "catalog",
            "baseName": "Catalog",
            "type": "ForecastCatalogRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ForecastDefinition.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}

