/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FirmwareDistributableRelationship } from './FirmwareDistributableRelationship';
import { HyperflexClusterProfileRelationship } from './HyperflexClusterProfileRelationship';
import { HyperflexSoftwareVersionPolicyAllOf } from './HyperflexSoftwareVersionPolicyAllOf';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { OrganizationOrganizationRelationship } from './OrganizationOrganizationRelationship';
import { PolicyAbstractPolicy } from './PolicyAbstractPolicy';
import { SoftwareHyperflexDistributableRelationship } from './SoftwareHyperflexDistributableRelationship';
import { HttpFile } from '../http/http';

/**
* A policy capturing software versions for different HyperFlex Cluster compatible components ( like HyperFlex Data Platform, Hypervisor, etc. ), that the user wishes to apply on the HyperFlex cluster.
*/
export class HyperflexSoftwareVersionPolicy extends PolicyAbstractPolicy {
    /**
    * Desired HyperFlex Data Platform software version to apply on the HyperFlex cluster.
    */
    'hxdpVersion'?: string;
    /**
    * Desired  hypervisor version to apply for all the nodes on the HyperFlex cluster.
    */
    'hypervisorVersion'?: string;
    /**
    * Desired server firmware version to apply on the HyperFlex Cluster.
    */
    'serverFirmwareVersion'?: string;
    'upgradeTypes'?: Array<HyperflexSoftwareVersionPolicyUpgradeTypesEnum>;
    /**
    * An array of relationships to hyperflexClusterProfile resources.
    */
    'clusterProfiles'?: Array<HyperflexClusterProfileRelationship>;
    'hxdpVersionInfo'?: SoftwareHyperflexDistributableRelationship;
    'hypervisorVersionInfo'?: SoftwareHyperflexDistributableRelationship;
    'organization'?: OrganizationOrganizationRelationship;
    'serverFirmwareVersionInfo'?: FirmwareDistributableRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hxdpVersion",
            "baseName": "HxdpVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "hypervisorVersion",
            "baseName": "HypervisorVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverFirmwareVersion",
            "baseName": "ServerFirmwareVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "upgradeTypes",
            "baseName": "UpgradeTypes",
            "type": "Array<HyperflexSoftwareVersionPolicyUpgradeTypesEnum>",
            "format": ""
        },
        {
            "name": "clusterProfiles",
            "baseName": "ClusterProfiles",
            "type": "Array<HyperflexClusterProfileRelationship>",
            "format": ""
        },
        {
            "name": "hxdpVersionInfo",
            "baseName": "HxdpVersionInfo",
            "type": "SoftwareHyperflexDistributableRelationship",
            "format": ""
        },
        {
            "name": "hypervisorVersionInfo",
            "baseName": "HypervisorVersionInfo",
            "type": "SoftwareHyperflexDistributableRelationship",
            "format": ""
        },
        {
            "name": "organization",
            "baseName": "Organization",
            "type": "OrganizationOrganizationRelationship",
            "format": ""
        },
        {
            "name": "serverFirmwareVersionInfo",
            "baseName": "ServerFirmwareVersionInfo",
            "type": "FirmwareDistributableRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(HyperflexSoftwareVersionPolicy.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}


export type HyperflexSoftwareVersionPolicyUpgradeTypesEnum = "NONE" | "Hxdp" | "Hypervisor" ;

