/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IamAccountRelationship } from './IamAccountRelationship';
import { IamIdpRelationship } from './IamIdpRelationship';
import { IamUserGroupRelationship } from './IamUserGroupRelationship';
import { IamUserPreferenceRelationship } from './IamUserPreferenceRelationship';
import { IamUserRelationship } from './IamUserRelationship';
import { HttpFile } from '../http/http';

/**
* Definition of the list of properties defined in 'iam.IdpReference', excluding properties defined in parent classes.
*/
export class IamIdpReferenceAllOf {
    /**
    * The email domain name for this IdP of the user. When a user enters an email during login in the Intersight home page, the IdP is picked by matching this domain name with the email domain name for authentication.
    */
    'domainName'?: string;
    /**
    * Entity ID of the IdP. In SAML, the entity ID uniquely identifies the IdP/Service Provider.
    */
    'idpEntityId'?: string;
    /**
    * The flag represents if the second factor of authentication is required for Cisco IdP users.
    */
    'multiFactorAuthentication'?: boolean;
    /**
    * Cisco IdP reference in an account.
    */
    'name'?: string;
    'account'?: IamAccountRelationship;
    'idp'?: IamIdpRelationship;
    /**
    * An array of relationships to iamUserPreference resources.
    */
    'userPreferences'?: Array<IamUserPreferenceRelationship>;
    /**
    * An array of relationships to iamUserGroup resources.
    */
    'usergroups'?: Array<IamUserGroupRelationship>;
    /**
    * An array of relationships to iamUser resources.
    */
    'users'?: Array<IamUserRelationship>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domainName",
            "baseName": "DomainName",
            "type": "string",
            "format": ""
        },
        {
            "name": "idpEntityId",
            "baseName": "IdpEntityId",
            "type": "string",
            "format": ""
        },
        {
            "name": "multiFactorAuthentication",
            "baseName": "MultiFactorAuthentication",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "Account",
            "type": "IamAccountRelationship",
            "format": ""
        },
        {
            "name": "idp",
            "baseName": "Idp",
            "type": "IamIdpRelationship",
            "format": ""
        },
        {
            "name": "userPreferences",
            "baseName": "UserPreferences",
            "type": "Array<IamUserPreferenceRelationship>",
            "format": ""
        },
        {
            "name": "usergroups",
            "baseName": "Usergroups",
            "type": "Array<IamUserGroupRelationship>",
            "format": ""
        },
        {
            "name": "users",
            "baseName": "Users",
            "type": "Array<IamUserRelationship>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IamIdpReferenceAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

