/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Definition of the list of properties defined in 'iam.LdapBaseProperties', excluding properties defined in parent classes.
*/
export class IamLdapBasePropertiesAllOf {
    /**
    * Role and locale information of the user.
    */
    'attribute'?: string;
    /**
    * Base Distinguished Name (DN). Starting point from where server will search for users and groups.
    */
    'baseDn'?: string;
    /**
    * Distinguished Name (DN) of the user, that is used to authenticate against LDAP servers.
    */
    'bindDn'?: string;
    /**
    * Authentication method to access LDAP servers.
    */
    'bindMethod'?: IamLdapBasePropertiesAllOfBindMethodEnum;
    /**
    * The IPv4 domain that all users must be in.
    */
    'domain'?: string;
    /**
    * If enabled, the endpoint encrypts all information it sends to the LDAP server.
    */
    'enableEncryption'?: boolean;
    /**
    * If enabled, user authorization is also done at the group level for LDAP users not in the local user database.
    */
    'enableGroupAuthorization'?: boolean;
    /**
    * Criteria to identify entries in search requests.
    */
    'filter'?: string;
    /**
    * Groups to which an LDAP entry belongs.
    */
    'groupAttribute'?: string;
    /**
    * Indicates whether the value of the 'password' property has been set.
    */
    'isPasswordSet'?: boolean;
    /**
    * Search depth to look for a nested LDAP group in an LDAP group map.
    */
    'nestedGroupSearchDepth'?: number;
    /**
    * Password of the user, that is used to authenticate.
    */
    'password'?: string;
    /**
    * LDAP authentication timeout duration, in seconds.
    */
    'timeout'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attribute",
            "baseName": "Attribute",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseDn",
            "baseName": "BaseDn",
            "type": "string",
            "format": ""
        },
        {
            "name": "bindDn",
            "baseName": "BindDn",
            "type": "string",
            "format": ""
        },
        {
            "name": "bindMethod",
            "baseName": "BindMethod",
            "type": "IamLdapBasePropertiesAllOfBindMethodEnum",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "Domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "enableEncryption",
            "baseName": "EnableEncryption",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "enableGroupAuthorization",
            "baseName": "EnableGroupAuthorization",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "Filter",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupAttribute",
            "baseName": "GroupAttribute",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPasswordSet",
            "baseName": "IsPasswordSet",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nestedGroupSearchDepth",
            "baseName": "NestedGroupSearchDepth",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "password",
            "baseName": "Password",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "Timeout",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return IamLdapBasePropertiesAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type IamLdapBasePropertiesAllOfBindMethodEnum = "LoginCredentials" | "Anonymous" | "ConfiguredCredentials" ;

