/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetDeviceRegistrationRelationship } from './AssetDeviceRegistrationRelationship';
import { StorageControllerRelationship } from './StorageControllerRelationship';
import { StoragePhysicalDiskUsageRelationship } from './StoragePhysicalDiskUsageRelationship';
import { StorageVdMemberEpRelationship } from './StorageVdMemberEpRelationship';
import { StorageVirtualDriveExtensionRelationship } from './StorageVirtualDriveExtensionRelationship';
import { HttpFile } from '../http/http';

/**
* Definition of the list of properties defined in 'storage.VirtualDrive', excluding properties defined in parent classes.
*/
export class StorageVirtualDriveAllOf {
    'accessPolicy'?: string;
    'actualWriteCachePolicy'?: string;
    'availableSize'?: string;
    'blockSize'?: string;
    'bootable'?: string;
    'configState'?: string;
    'configuredWriteCachePolicy'?: string;
    'connectionProtocol'?: string;
    'driveCache'?: string;
    'driveSecurity'?: string;
    /**
    * It shows the Virtual drive state.
    */
    'driveState'?: string;
    'ioPolicy'?: string;
    'name'?: string;
    'numBlocks'?: string;
    /**
    * It shows the current operational state of Virtual drive.
    */
    'operState'?: string;
    'operability'?: string;
    'physicalBlockSize'?: string;
    'presence'?: string;
    'readPolicy'?: string;
    'securityFlags'?: string;
    'size'?: string;
    /**
    * The strip size is the portion of a stripe that resides on a single drive in the drive group, this is measured in KB.
    */
    'stripSize'?: string;
    'type'?: string;
    'uuid'?: string;
    'vendorUuid'?: string;
    'virtualDriveId'?: string;
    /**
    * An array of relationships to storagePhysicalDiskUsage resources.
    */
    'physicalDiskUsages'?: Array<StoragePhysicalDiskUsageRelationship>;
    'registeredDevice'?: AssetDeviceRegistrationRelationship;
    'storageController'?: StorageControllerRelationship;
    /**
    * An array of relationships to storageVdMemberEp resources.
    */
    'vdMemberEps'?: Array<StorageVdMemberEpRelationship>;
    'virtualDriveExtension'?: StorageVirtualDriveExtensionRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessPolicy",
            "baseName": "AccessPolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "actualWriteCachePolicy",
            "baseName": "ActualWriteCachePolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "availableSize",
            "baseName": "AvailableSize",
            "type": "string",
            "format": ""
        },
        {
            "name": "blockSize",
            "baseName": "BlockSize",
            "type": "string",
            "format": ""
        },
        {
            "name": "bootable",
            "baseName": "Bootable",
            "type": "string",
            "format": ""
        },
        {
            "name": "configState",
            "baseName": "ConfigState",
            "type": "string",
            "format": ""
        },
        {
            "name": "configuredWriteCachePolicy",
            "baseName": "ConfiguredWriteCachePolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionProtocol",
            "baseName": "ConnectionProtocol",
            "type": "string",
            "format": ""
        },
        {
            "name": "driveCache",
            "baseName": "DriveCache",
            "type": "string",
            "format": ""
        },
        {
            "name": "driveSecurity",
            "baseName": "DriveSecurity",
            "type": "string",
            "format": ""
        },
        {
            "name": "driveState",
            "baseName": "DriveState",
            "type": "string",
            "format": ""
        },
        {
            "name": "ioPolicy",
            "baseName": "IoPolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "numBlocks",
            "baseName": "NumBlocks",
            "type": "string",
            "format": ""
        },
        {
            "name": "operState",
            "baseName": "OperState",
            "type": "string",
            "format": ""
        },
        {
            "name": "operability",
            "baseName": "Operability",
            "type": "string",
            "format": ""
        },
        {
            "name": "physicalBlockSize",
            "baseName": "PhysicalBlockSize",
            "type": "string",
            "format": ""
        },
        {
            "name": "presence",
            "baseName": "Presence",
            "type": "string",
            "format": ""
        },
        {
            "name": "readPolicy",
            "baseName": "ReadPolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "securityFlags",
            "baseName": "SecurityFlags",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "Size",
            "type": "string",
            "format": ""
        },
        {
            "name": "stripSize",
            "baseName": "StripSize",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "Type",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "Uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "vendorUuid",
            "baseName": "VendorUuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "virtualDriveId",
            "baseName": "VirtualDriveId",
            "type": "string",
            "format": ""
        },
        {
            "name": "physicalDiskUsages",
            "baseName": "PhysicalDiskUsages",
            "type": "Array<StoragePhysicalDiskUsageRelationship>",
            "format": ""
        },
        {
            "name": "registeredDevice",
            "baseName": "RegisteredDevice",
            "type": "AssetDeviceRegistrationRelationship",
            "format": ""
        },
        {
            "name": "storageController",
            "baseName": "StorageController",
            "type": "StorageControllerRelationship",
            "format": ""
        },
        {
            "name": "vdMemberEps",
            "baseName": "VdMemberEps",
            "type": "Array<StorageVdMemberEpRelationship>",
            "format": ""
        },
        {
            "name": "virtualDriveExtension",
            "baseName": "VirtualDriveExtension",
            "type": "StorageVirtualDriveExtensionRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StorageVirtualDriveAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

