/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TelemetryDruidArithmeticPostAggregatorAllOf } from './TelemetryDruidArithmeticPostAggregatorAllOf';
import { TelemetryDruidBasePostAggregator } from './TelemetryDruidBasePostAggregator';
import { HttpFile } from '../http/http';

/**
* The arithmetic post-aggregator applies the provided function to the given fields from left to right. The fields can be aggregators or other post aggregators. Supported functions are +, -, *, /, and quotient. / division always returns 0 if dividing by 0, regardless of the numerator. quotient division behaves like regular floating point division.
*/
export class TelemetryDruidArithmeticPostAggregator {
    /**
    * The post-aggregator type.
    */
    'type': string;
    /**
    * Output name for the minimum/maximum timestamp value.
    */
    'name'?: string;
    /**
    * null
    */
    'fn'?: TelemetryDruidArithmeticPostAggregatorFnEnum;
    /**
    * null
    */
    'fields'?: Array<string>;
    /**
    * Arithmetic post-aggregators may specify an ordering, which defines the order of resulting values when sorting results. This can be useful for topN queries for instance. If no ordering (or null) is specified, the default floating point ordering is used. numericFirst ordering always returns finite values first, followed by NaN, and infinite values last.
    */
    'ordering'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fn",
            "baseName": "fn",
            "type": "TelemetryDruidArithmeticPostAggregatorFnEnum",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "ordering",
            "baseName": "ordering",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TelemetryDruidArithmeticPostAggregator.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type TelemetryDruidArithmeticPostAggregatorFnEnum = "+" | "-" | "*" | "/" | "quotient" ;

