/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TelemetryDruidAggregator } from './TelemetryDruidAggregator';
import { TelemetryDruidBaseRequest } from './TelemetryDruidBaseRequest';
import { TelemetryDruidDataSource } from './TelemetryDruidDataSource';
import { TelemetryDruidDefaultLimitSpec } from './TelemetryDruidDefaultLimitSpec';
import { TelemetryDruidDimensionSpec } from './TelemetryDruidDimensionSpec';
import { TelemetryDruidFilter } from './TelemetryDruidFilter';
import { TelemetryDruidGranularity } from './TelemetryDruidGranularity';
import { TelemetryDruidGroupByRequestAllOf } from './TelemetryDruidGroupByRequestAllOf';
import { TelemetryDruidHavingFilter } from './TelemetryDruidHavingFilter';
import { TelemetryDruidPostAggregator } from './TelemetryDruidPostAggregator';
import { TelemetryDruidQueryContext } from './TelemetryDruidQueryContext';
import { HttpFile } from '../http/http';

/**
* These types of Apache Druid queries take a groupBy query object and return an array of JSON objects where each object represents a grouping asked for by the query.
*/
export class TelemetryDruidGroupByRequest {
    /**
    * null
    */
    'queryType': string;
    'dataSource': TelemetryDruidDataSource;
    /**
    * A JSON list of dimensions to do the groupBy over; or see DimensionSpec for ways to extract dimensions..
    */
    'dimensions': Array<TelemetryDruidDimensionSpec>;
    'limitSpec'?: TelemetryDruidDefaultLimitSpec;
    'having'?: TelemetryDruidHavingFilter;
    'granularity': TelemetryDruidGranularity;
    'filter'?: TelemetryDruidFilter;
    'aggregations'?: TelemetryDruidAggregator;
    'postAggregations'?: TelemetryDruidPostAggregator;
    /**
    * A JSON Object representing ISO-8601 Intervals. This defines the time ranges to run the query over.
    */
    'intervals': Array<string>;
    /**
    * A JSON array of arrays to return additional result sets for groupings of subsets of top level dimensions. The subtotals feature allows computation of multiple sub-groupings in a single query. To use this feature, add a \"subtotalsSpec\" to your query, which should be a list of subgroup dimension sets. It should contain the \"outputName\" from dimensions in your \"dimensions\" attribute, in the same order as they appear in the \"dimensions\" attribute.
    */
    'subtotalsSpec'?: any;
    'context'?: TelemetryDruidQueryContext;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queryType",
            "baseName": "queryType",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataSource",
            "baseName": "dataSource",
            "type": "TelemetryDruidDataSource",
            "format": ""
        },
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "Array<TelemetryDruidDimensionSpec>",
            "format": ""
        },
        {
            "name": "limitSpec",
            "baseName": "limitSpec",
            "type": "TelemetryDruidDefaultLimitSpec",
            "format": ""
        },
        {
            "name": "having",
            "baseName": "having",
            "type": "TelemetryDruidHavingFilter",
            "format": ""
        },
        {
            "name": "granularity",
            "baseName": "granularity",
            "type": "TelemetryDruidGranularity",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "TelemetryDruidFilter",
            "format": ""
        },
        {
            "name": "aggregations",
            "baseName": "aggregations",
            "type": "TelemetryDruidAggregator",
            "format": ""
        },
        {
            "name": "postAggregations",
            "baseName": "postAggregations",
            "type": "TelemetryDruidPostAggregator",
            "format": ""
        },
        {
            "name": "intervals",
            "baseName": "intervals",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "subtotalsSpec",
            "baseName": "subtotalsSpec",
            "type": "any",
            "format": ""
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "TelemetryDruidQueryContext",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TelemetryDruidGroupByRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

