/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MoBaseComplexType } from './MoBaseComplexType';
import { VirtualizationComputeCapacityAllOf } from './VirtualizationComputeCapacityAllOf';
import { HttpFile } from '../http/http';

/**
* Details of available CPU power across all cores and the free capacity still available.
*/
export class VirtualizationComputeCapacity extends MoBaseComplexType {
    /**
    * Total capacity of the entity in MHz.
    */
    'capacity'?: number;
    /**
    * Free CPU capacity in MHz, as a point-in-time snapshot. The available CPU capacity is reported for an entity (such as Host or Cluster) when inventory data is collected for that entity. As part of the inventory data, a snapshot of the free and used CPU capacity is also reported.
    */
    'free'?: number;
    /**
    * Used CPU capacity of the entity in MHz, as a point-in-time snapshot.
    */
    'used'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "capacity",
            "baseName": "Capacity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "free",
            "baseName": "Free",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "used",
            "baseName": "Used",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VirtualizationComputeCapacity.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}

