/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetDeviceRegistrationRelationship } from './AssetDeviceRegistrationRelationship';
import { InfraHardwareInfo } from './InfraHardwareInfo';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { VirtualizationComputeCapacity } from './VirtualizationComputeCapacity';
import { VirtualizationCpuInfo } from './VirtualizationCpuInfo';
import { VirtualizationHostAllOf } from './VirtualizationHostAllOf';
import { VirtualizationMemoryCapacity } from './VirtualizationMemoryCapacity';
import { VirtualizationProductInfo } from './VirtualizationProductInfo';
import { VirtualizationSourceDevice } from './VirtualizationSourceDevice';
import { HttpFile } from '../http/http';

/**
* Common attributes of any host associated to a hypervisor manager. Serves as a base class for all concrete host types A Host belongs to a datacenter and optionally to a cluster, and runs virtual machines on it. A host is basically a hardware platform that runs the VMs. Depending on the capacity of the host, it can support 100s of virtual machines.
*/
export class VirtualizationHost extends VirtualizationSourceDevice {
    'cpuInfo'?: VirtualizationCpuInfo;
    'hardwareInfo'?: InfraHardwareInfo;
    /**
    * Identifies the broad type of the underlying hypervisor.
    */
    'hypervisorType'?: VirtualizationHostHypervisorTypeEnum;
    /**
    * The internally generated identity of this host. This entity is not manipulated by users. It aids in uniquely identifying the datacenter object. For VMware, this is an MOR (managed object reference).
    */
    'identity'?: string;
    /**
    * Is this host in maintenance mode. Set to true or false.
    */
    'maintenanceMode'?: boolean;
    'memoryCapacity'?: VirtualizationMemoryCapacity;
    /**
    * Commercial model information about this hardware.
    */
    'model'?: string;
    /**
    * Name of this host supplied by user. It is not the identity of the host. The name is subject to user manipulations.
    */
    'name'?: string;
    'processorCapacity'?: VirtualizationComputeCapacity;
    'productInfo'?: VirtualizationProductInfo;
    /**
    * Serial number of this host (internally generated).
    */
    'serial'?: string;
    /**
    * Host health status, as reported by the hypervisor platform.
    */
    'status'?: VirtualizationHostStatusEnum;
    /**
    * The uptime of the host, stored as Duration (from w3c).
    */
    'upTime'?: string;
    /**
    * Universally unique identity of this host (example b3d4483b-5560-9342-8309-b486c9236610). Internally generated.
    */
    'uuid'?: string;
    /**
    * Commercial vendor details of this hardware.
    */
    'vendor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cpuInfo",
            "baseName": "CpuInfo",
            "type": "VirtualizationCpuInfo",
            "format": ""
        },
        {
            "name": "hardwareInfo",
            "baseName": "HardwareInfo",
            "type": "InfraHardwareInfo",
            "format": ""
        },
        {
            "name": "hypervisorType",
            "baseName": "HypervisorType",
            "type": "VirtualizationHostHypervisorTypeEnum",
            "format": ""
        },
        {
            "name": "identity",
            "baseName": "Identity",
            "type": "string",
            "format": ""
        },
        {
            "name": "maintenanceMode",
            "baseName": "MaintenanceMode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "memoryCapacity",
            "baseName": "MemoryCapacity",
            "type": "VirtualizationMemoryCapacity",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "Model",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "processorCapacity",
            "baseName": "ProcessorCapacity",
            "type": "VirtualizationComputeCapacity",
            "format": ""
        },
        {
            "name": "productInfo",
            "baseName": "ProductInfo",
            "type": "VirtualizationProductInfo",
            "format": ""
        },
        {
            "name": "serial",
            "baseName": "Serial",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "Status",
            "type": "VirtualizationHostStatusEnum",
            "format": ""
        },
        {
            "name": "upTime",
            "baseName": "UpTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "Uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "vendor",
            "baseName": "Vendor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VirtualizationHost.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}


export type VirtualizationHostHypervisorTypeEnum = "Unknown" | "ESXi" ;
export type VirtualizationHostStatusEnum = "Unknown" | "Degraded" | "Critical" | "Ok" ;

