/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MoBaseComplexType } from './MoBaseComplexType';
import { VnicEthInterruptSettingsAllOf } from './VnicEthInterruptSettingsAllOf';
import { HttpFile } from '../http/http';

/**
* Interrupt settings for the virtual ethernet interface.
*/
export class VnicEthInterruptSettings extends MoBaseComplexType {
    /**
    * The time to wait between interrupts or the idle period that must be encountered before an interrupt is sent. To turn off interrupt coalescing, enter 0 (zero) in this field.
    */
    'coalescingTime'?: number;
    /**
    * Interrupt Coalescing Type. This can be one of the following:- MIN  - The system waits for the time specified in the Coalescing Time field before sending another interrupt event IDLE - The system does not send an interrupt until there is a period of no activity lasting as least as long as the time specified in the Coalescing Time field.
    */
    'coalescingType'?: VnicEthInterruptSettingsCoalescingTypeEnum;
    /**
    * The number of interrupt resources to allocate. Typical value is be equal to the number of completion queue resources.
    */
    'count'?: number;
    /**
    * Preferred driver interrupt mode. This can be one of the following:- MSIx - Message Signaled Interrupts (MSI) with the optional extension. MSI  - MSI only. INTx - PCI INTx interrupts. MSIx is the recommended option.
    */
    'mode'?: VnicEthInterruptSettingsModeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coalescingTime",
            "baseName": "CoalescingTime",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "coalescingType",
            "baseName": "CoalescingType",
            "type": "VnicEthInterruptSettingsCoalescingTypeEnum",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "Count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "mode",
            "baseName": "Mode",
            "type": "VnicEthInterruptSettingsModeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VnicEthInterruptSettings.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}


export type VnicEthInterruptSettingsCoalescingTypeEnum = "MIN" | "IDLE" ;
export type VnicEthInterruptSettingsModeEnum = "MSIx" | "MSI" | "INTx" ;

