/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { OrganizationOrganizationRelationship } from './OrganizationOrganizationRelationship';
import { PolicyAbstractPolicy } from './PolicyAbstractPolicy';
import { VnicEthQosPolicyAllOf } from './VnicEthQosPolicyAllOf';
import { HttpFile } from '../http/http';

/**
* An Ethernet Quality of Service (QoS) policy assigns a system class to the outgoing traffic for a vNIC. This system class determines the quality of service for the outgoing traffic. For certain adapters you can also specify additional controls like burst and rate on the outgoing traffic.
*/
export class VnicEthQosPolicy extends PolicyAbstractPolicy {
    /**
    * Class of Service to be associated to the traffic on the virtual interface.
    */
    'cos'?: number;
    /**
    * The Maximum Transmission Unit (MTU) or packet size that the virtual interface accepts.
    */
    'mtu'?: number;
    /**
    * The value in Mbps (0-100000) to use for limiting the data rate on the virtual interface. Setting this to zero will turn rate limiting off.
    */
    'rateLimit'?: number;
    /**
    * Enables usage of the Class of Service provided by the operating system.
    */
    'trustHostCos'?: boolean;
    'organization'?: OrganizationOrganizationRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cos",
            "baseName": "Cos",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "mtu",
            "baseName": "Mtu",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "rateLimit",
            "baseName": "RateLimit",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "trustHostCos",
            "baseName": "TrustHostCos",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "organization",
            "baseName": "Organization",
            "type": "OrganizationOrganizationRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VnicEthQosPolicy.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}

