/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkflowCatalogRelationship } from './WorkflowCatalogRelationship';
import { WorkflowInternalProperties } from './WorkflowInternalProperties';
import { WorkflowProperties } from './WorkflowProperties';
import { WorkflowTaskDefinitionRelationship } from './WorkflowTaskDefinitionRelationship';
import { HttpFile } from '../http/http';

/**
* Definition of the list of properties defined in 'workflow.TaskDefinition', excluding properties defined in parent classes.
*/
export class WorkflowTaskDefinitionAllOf {
    /**
    * When true this will be the task version that is used when a specific task definition version is not specified. The very first task definition created with a name will be set as the default version, after that user can explicitly set any version of the task definition as the default version.
    */
    'defaultVersion'?: boolean;
    /**
    * The task definition description to describe what this task will do when executed.
    */
    'description'?: string;
    'internalProperties'?: WorkflowInternalProperties;
    /**
    * A user friendly short name to identify the task definition.
    */
    'label'?: string;
    /**
    * License entitlement required to run this task. It is determined by license requirement of features.
    */
    'licenseEntitlement'?: WorkflowTaskDefinitionAllOfLicenseEntitlementEnum;
    /**
    * The name of the task definition. The name should follow this convention <Verb or Action><Category><Vendor><Product><Noun or object> Verb or Action is a required portion of the name and this must be part of the pre-approved verb list. Category is an optional field and this will refer to the broad category of the task referring to the type of resource or endpoint. If there is no specific category then use \"Generic\" if required. Vendor is an optional field and this will refer to the specific vendor this task applies to. If the task is generic and not tied to a vendor, then do not specify anything. Product is an optional field, this will contain the vendor product and model when desired. Noun or object is a required field and  this will contain the noun or object on which the action is being performed. Examples SendEmail  - This is a task in Generic category for sending email. NewStorageVolume - This is a vendor agnostic task under Storage device category for creating a new volume.
    */
    'name'?: string;
    'properties'?: WorkflowProperties;
    /**
    * If set to true, the task requires access to secure properties and uses an encyption token associated with a workflow moid to encrypt or decrypt the secure properties.
    */
    'securePropAccess'?: boolean;
    /**
    * The version of the task definition so we can support multiple versions of a task definition.
    */
    'version'?: number;
    'catalog'?: WorkflowCatalogRelationship;
    /**
    * An array of relationships to workflowTaskDefinition resources.
    */
    'implementedTasks'?: Array<WorkflowTaskDefinitionRelationship>;
    'interfaceTask'?: WorkflowTaskDefinitionRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultVersion",
            "baseName": "DefaultVersion",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "internalProperties",
            "baseName": "InternalProperties",
            "type": "WorkflowInternalProperties",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "Label",
            "type": "string",
            "format": ""
        },
        {
            "name": "licenseEntitlement",
            "baseName": "LicenseEntitlement",
            "type": "WorkflowTaskDefinitionAllOfLicenseEntitlementEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "Properties",
            "type": "WorkflowProperties",
            "format": ""
        },
        {
            "name": "securePropAccess",
            "baseName": "SecurePropAccess",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "Version",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "catalog",
            "baseName": "Catalog",
            "type": "WorkflowCatalogRelationship",
            "format": ""
        },
        {
            "name": "implementedTasks",
            "baseName": "ImplementedTasks",
            "type": "Array<WorkflowTaskDefinitionRelationship>",
            "format": ""
        },
        {
            "name": "interfaceTask",
            "baseName": "InterfaceTask",
            "type": "WorkflowTaskDefinitionRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowTaskDefinitionAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type WorkflowTaskDefinitionAllOfLicenseEntitlementEnum = "Base" | "Essential" | "Standard" | "Advantage" | "Premier" ;

