/**
 * Cisco Intersight
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-05-14T14:50:55-07:00.
 *
 * OpenAPI spec version: 1.0.9-1731
 * Contact: intersight@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MoBaseMo } from './MoBaseMo';
import { MoBaseMoRelationship } from './MoBaseMoRelationship';
import { MoTag } from './MoTag';
import { MoVersionContext } from './MoVersionContext';
import { WorkflowBaseDataType } from './WorkflowBaseDataType';
import { WorkflowCatalogRelationship } from './WorkflowCatalogRelationship';
import { WorkflowCustomDataTypeDefinitionAllOf } from './WorkflowCustomDataTypeDefinitionAllOf';
import { HttpFile } from '../http/http';

/**
* Captures a customized data type definition that can be used for task or workflow input/output.  This can be reused across multiple tasks and workflow definitions.
*/
export class WorkflowCustomDataTypeDefinition extends MoBaseMo {
    /**
    * When true this data type definition is a collection of type definitions to represent composite data like JSON.
    */
    'compositeType'?: boolean;
    /**
    * A human-friendly description of this custom data type indicating it's domain and usage.
    */
    'description'?: string;
    /**
    * A user friendly short name to identify the custom data type definition.
    */
    'label'?: string;
    /**
    * The name of custom data type definition. The valid name can contain lower case and upper case alphabetic characters, degits and special characters '-' and '_'.
    */
    'name'?: string;
    'typeDefinition'?: Array<WorkflowBaseDataType>;
    'catalog'?: WorkflowCatalogRelationship;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "compositeType",
            "baseName": "CompositeType",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "Label",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeDefinition",
            "baseName": "TypeDefinition",
            "type": "Array<WorkflowBaseDataType>",
            "format": ""
        },
        {
            "name": "catalog",
            "baseName": "Catalog",
            "type": "WorkflowCatalogRelationship",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WorkflowCustomDataTypeDefinition.attributeTypeMap);
    }
    
    public constructor() {
        super();
    }
}

